// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValhallaVaultCyberAwareness.Data;

#nullable disable

namespace ValhallaVaultCyberAwareness.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240305132001_newCreate")]
    partial class newCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.AnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrectAnswer = false,
                            QuestionId = 1,
                            Text = "Ett legitimt försök från banken att skydda ditt konto"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrectAnswer = false,
                            QuestionId = 1,
                            Text = "En informationsinsamling för en marknadsundersökning"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrectAnswer = true,
                            QuestionId = 1,
                            Text = "Ett potentiellt telefonbedrägeri"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrectAnswer = false,
                            QuestionId = 2,
                            Text = "En legitim begäran om hjälp från en person i nöd"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrectAnswer = true,
                            QuestionId = 2,
                            Text = "Ett romansbedrägeri"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrectAnswer = false,
                            QuestionId = 2,
                            Text = "En tillfällig ekonomisk svårighet"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrectAnswer = false,
                            QuestionId = 3,
                            Text = "Genomföra omedelbar investering för att inte missa möjligheten"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrectAnswer = false,
                            QuestionId = 3,
                            Text = "Investeringsbedrägeri"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrectAnswer = false,
                            QuestionId = 3,
                            Text = "Begära mer information för att utföra en noggrann ‘’due diligence’’"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrectAnswer = false,
                            QuestionId = 4,
                            Text = "Ett misstag av kreditkortsföretaget"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrectAnswer = true,
                            QuestionId = 4,
                            Text = "Kreditkortsbedrägeri"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrectAnswer = false,
                            QuestionId = 4,
                            Text = "Obehöriga köp av en familjemedlem"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrectAnswer = true,
                            QuestionId = 5,
                            Text = "Utbildning i digital säkerhet för alla anställda"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrectAnswer = false,
                            QuestionId = 5,
                            Text = "Installera en starkare brandvägg"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrectAnswer = false,
                            QuestionId = 5,
                            Text = " Byta ut all IT-utrustning"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrectAnswer = true,
                            QuestionId = 6,
                            Text = " Informera alla användare om sårbarheten och rekommendera temporära skyddsåtgärder"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrectAnswer = false,
                            QuestionId = 6,
                            Text = "Ignorera problemet tills en patch kan utvecklas"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrectAnswer = true,
                            QuestionId = 6,
                            Text = "Stänga ner tjänsten tillfälligt"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrectAnswer = false,
                            QuestionId = 7,
                            Text = "En enskild hackare med ett personligt vendetta"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrectAnswer = false,
                            QuestionId = 7,
                            Text = "En konkurrerande företagsentitet"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrectAnswer = true,
                            QuestionId = 7,
                            Text = "Organiserade cyberbrottsliga grupper"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrectAnswer = true,
                            QuestionId = 8,
                            Text = "Återgå till kontorsarbete"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrectAnswer = false,
                            QuestionId = 8,
                            Text = "Införa striktare lösenordspolicyer och tvåfaktorsautentisering för fjärråtkomst"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrectAnswer = false,
                            QuestionId = 8,
                            Text = "Förbjuda användning av personliga enheter för arbete"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrectAnswer = false,
                            QuestionId = 9,
                            Text = "Phishing"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrectAnswer = true,
                            QuestionId = 9,
                            Text = "Ransomware"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrectAnswer = false,
                            QuestionId = 9,
                            Text = "Spyware"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrectAnswer = false,
                            QuestionId = 10,
                            Text = "Spyware"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrectAnswer = true,
                            QuestionId = 10,
                            Text = "Ransomware"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrectAnswer = false,
                            QuestionId = 10,
                            Text = "Adware"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrectAnswer = false,
                            QuestionId = 11,
                            Text = "Cyberkriminalitet"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrectAnswer = true,
                            QuestionId = 11,
                            Text = "Cyberspionage"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrectAnswer = false,
                            QuestionId = 11,
                            Text = "Cyberterrorism"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrectAnswer = false,
                            QuestionId = 12,
                            Text = "Social ingenjörskonst"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrectAnswer = false,
                            QuestionId = 12,
                            Text = "Massövervakning"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrectAnswer = true,
                            QuestionId = 12,
                            Text = "Riktade cyberattacker"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrectAnswer = false,
                            QuestionId = 13,
                            Text = "GDPR"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrectAnswer = true,
                            QuestionId = 13,
                            Text = "Säkerhetsskyddslagen"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrectAnswer = false,
                            QuestionId = 13,
                            Text = "IT-säkerhetslagen"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrectAnswer = false,
                            QuestionId = 14,
                            Text = "Oberoende hackare"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrectAnswer = false,
                            QuestionId = 14,
                            Text = "Aktivistgrupper"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrectAnswer = true,
                            QuestionId = 14,
                            Text = "Statssponsrade hackers"
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Att skydda sig mot bedrägerier"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cyberspionage"
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExplanationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExplanationText = "Banker och andra finansiella institutioner begär aldrig känslig information såsom kontonummer eller lösenord via telefon. Detta är ett klassiskt tecken på telefonbedrägeri.",
                            SegmentId = 1,
                            Text = "Du får ett oväntat telefonsamtal från någon som påstår sig vara från din bank. Personen ber dig bekräfta ditt kontonummer och lösenord för att \"säkerställa din kontos säkerhet\" efter en påstådd säkerhetsincident. Hur bör du tolka denna situation?",
                            Title = "Kreditkortsbedrägeri"
                        },
                        new
                        {
                            Id = 2,
                            ExplanationText = "Begäran om pengar, särskilt under omständigheter där två personer aldrig har träffats fysiskt, är ett vanligt tecken på romansbedrägeri.",
                            SegmentId = 1,
                            Text = "Efter flera månader av daglig kommunikation med någon du träffade på en datingsida, börjar personen berätta om en plötslig finansiell kris och ber om din hjälp genom att överföra pengar. Vad indikerar detta mest sannolikt?",
                            Title = "Romansbedrägeri"
                        },
                        new
                        {
                            Id = 3,
                            ExplanationText = "Erbjudanden som lovar hög avkastning med liten eller ingen risk, särskilt via oönskade e-postmeddelanden, är ofta tecken på investeringsbedrägerier",
                            SegmentId = 1,
                            Text = "Du får ett e-postmeddelande/samtal om ett exklusivt erbjudande att investera i ett startup-företag som påstås ha en revolutionerande ny teknologi, med garantier om exceptionellt hög avkastning på mycket kort tid. Hur bör du förhålla dig till erbjudandet?",
                            Title = "Investeringsbedrägeri"
                        },
                        new
                        {
                            Id = 4,
                            ExplanationText = "Oidentifierade transaktioner på ditt kreditkortsutdrag är en stark indikation på att ditt kortnummer har komprometterats och använts för obehöriga köp, vilket är typiskt för kreditkortsbedrägeri",
                            SegmentId = 1,
                            Text = "Efter en online-shoppingrunda märker du oidentifierade transaktioner på ditt kreditkortsutdrag från företag du aldrig handlat från. Vad indikerar detta mest sannolikt?",
                            Title = "Telefonbedrägeri"
                        },
                        new
                        {
                            Id = 5,
                            ExplanationText = "Utbildning i digital säkerhet är avgörande för att hjälpa anställda att känna igen och undvika säkerhetshot som phishing, vilket är en vanlig attackvektor.",
                            SegmentId = 4,
                            Text = "Inom företaget märker man att konfidentiella dokument regelbundet läcker ut till konkurrenter. Efter en intern granskning upptäcks det att en anställd omedvetet har installerat skadlig programvara genom att klicka på en länk i ett phishing-e-postmeddelande. Vilken åtgärd bör prioriteras för att förhindra framtida incidenter?",
                            Title = "Digital säkerhet på företag"
                        },
                        new
                        {
                            Id = 6,
                            ExplanationText = "Transparent kommunikation och rådgivning om tillfälliga åtgärder är avgörande för att skydda användarna medan en permanent lösning utvecklas.",
                            SegmentId = 4,
                            Text = "Inom företaget upptäckts det en sårbarhet i vår programvara som kunde möjliggöra obehörig åtkomst till användardata. Företaget har inte omedelbart en lösning. Vilken är den mest lämpliga första åtgärden?",
                            Title = "Risker och beredskap"
                        },
                        new
                        {
                            Id = 7,
                            ExplanationText = "DDoS-attacker kräver ofta betydande resurser och koordinering, vilket är karakteristiskt för organiserade cyberbrottsliga grupper.",
                            SegmentId = 4,
                            Text = "Vårt företag blir måltavla för en DDoS-attack som överväldigar våra servers och gör våra tjänster otillgängliga för kunder. Vilken typ av aktör är mest sannolikt ansvarig för denna typ av attack?",
                            Title = "Aktörer inom cyberbrott"
                        },
                        new
                        {
                            Id = 8,
                            ExplanationText = " Stärkt autentisering är kritisk för att säkra fjärråtkomst och skydda mot obehörig åtkomst i en distribuerad arbetsmiljö.",
                            SegmentId = 4,
                            Text = "Med övergången till distansarbete upptäcker vårt företag en ökning av säkerhetsincidenter, inklusive obehörig åtkomst till företagsdata. Vilken åtgärd bör företaget vidta för att adressera denna nya riskmiljö?",
                            Title = "Ökad digital närvaro och distansarbete"
                        },
                        new
                        {
                            Id = 9,
                            ExplanationText = "Ransomware-angrepp involverar kryptering av offerdata och kräver lösen för dekryptering, vilket är särskilt skadligt för kritiska sektorer som hälsovård.",
                            SegmentId = 4,
                            Text = "Hälsovårdsmyndigheten utsätts för ett cyberangrepp som krypterar patientdata och kräver lösen för att återställa åtkomsten. Vilken typ av angrepp har de sannolikt blivit utsatta för?",
                            Title = "Cyberangrepp mot känsliga sektorer"
                        },
                        new
                        {
                            Id = 10,
                            ExplanationText = "Maersk utsattes för NotPetya ransomware-angreppet, som ledde till omfattande störningar och förluster genom att kryptera företagets globala system. Maersk rapporterade att företaget led ekonomiska förluster på grund av NotPetya ransomware-angreppet som uppskattades till cirka 300 miljoner USD. Denna siffra reflekterar de omfattande kostnaderna för störningar i deras globala verksamheter, återställande av system och data, samt förlust av affärer under tiden systemen var nere. NotPetya-angreppet anses vara ett av de mest kostsamma cyberangreppen mot ett enskilt företag och tjänar som en kraftfull påminnelse om de potentiella konsekvenserna av cyberhot.",
                            SegmentId = 4,
                            Text = "Det globala fraktbolaget Maersk blev offer för ett omfattande cyberangrepp som avsevärt störde deras verksamhet världen över. Vilken typ av malware var primärt ansvarig för denna incident?",
                            Title = "Cyberrånet mot Mersk"
                        },
                        new
                        {
                            Id = 11,
                            ExplanationText = " Cyberspionage avser aktiviteter där aktörer, ofta statliga, engagerar sig i övervakning och datainsamling genom cybermedel för att erhålla hemlig information utan målets medgivande, typiskt för politiska, militära eller ekonomiska fördelar.",
                            SegmentId = 8,
                            Text = "Regeringen upptäcker att känslig politisk kommunikation har läckt och misstänker elektronisk övervakning. Vilket fenomen beskriver bäst denna situation?",
                            Title = "Allmänt om cyberspionage"
                        },
                        new
                        {
                            Id = 12,
                            ExplanationText = "Riktade cyberattacker som utnyttjar noll-dagars Zero-day sårbarheter är en avancerad metod för cyberspionage där angriparen specifikt riktar in sig på ett mål för att komma åt känslig information eller data genom att utnyttja tidigare okända sårbarheter i programvara.",
                            SegmentId = 8,
                            Text = "Regeringen blir varse om en sofistikerad skadeprogramskampanj som utnyttjar Zero-day sårbarheter för att infiltrera deras nätverk och stjäla oerhört viktig data. Vilken metod för cyberspionage används sannolikt här?",
                            Title = "Metoder för cyberspionage"
                        },
                        new
                        {
                            Id = 13,
                            ExplanationText = "Säkerhetsskyddslagen är en svensk lagstiftning som syftar till att skydda nationellt känslig information från spioneri, sabotage, terroristbrott och andra säkerhetshot. Lagen ställer krav på säkerhetsskyddsåtgärder för verksamheter av betydelse för Sveriges säkerhet.",
                            SegmentId = 8,
                            Text = "Regeringen i Sverige ökar sitt interna säkerhetsprotokoll för att skydda sig mot utländska underrättelsetjänsters infiltration. Vilken lagstiftning ger ramverket för detta skydd?",
                            Title = "Säkerhetsskyddslagen"
                        },
                        new
                        {
                            Id = 14,
                            ExplanationText = "Lunds universitet upptäcker att forskningsdata om ny teknologi har stulits. Undersökningar tyder på en välorganiserad grupp med kopplingar till en utländsk stat. Vilken typ av aktör ligger sannolikt bakom detta?",
                            SegmentId = 8,
                            Text = "Statssponsrade hackers är aktörer som arbetar på uppdrag av eller med stöd från en regering för att genomföra cyberspionage, ofta riktat mot utländska intressen, organisationer eller regeringar för att få strategiska fördelar.",
                            Title = "Cyberspionagets aktörer"
                        });
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.ResponseModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnsweredCorrectly")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.SegmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("InfoText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Segments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Del 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Del 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Del 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Del 1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Del 2"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Del 3"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Del 4"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Del 1"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Del 2"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Del 3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.AnswerModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Models.QuestionModel", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.QuestionModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Models.SegmentModel", "Segment")
                        .WithMany("Questions")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.ResponseModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Models.QuestionModel", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValhallaVaultCyberAwareness.Data.ApplicationUser", "User")
                        .WithMany("Responses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.SegmentModel", b =>
                {
                    b.HasOne("ValhallaVaultCyberAwareness.Models.CategoryModel", "Category")
                        .WithMany("Segments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Data.ApplicationUser", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.CategoryModel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.QuestionModel", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("ValhallaVaultCyberAwareness.Models.SegmentModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
